import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style= {{ 
          backgroundColor: "#eeeeee",
          padding: "1rem",
          color: "#71a0a5", 
          fontFamily: "verdana",
        }}
        ><p>Browse Games </p>
        <p> How It Works </p>
        <p>About</p>
        </header>
        {children}
        </body>
    </html>
  )
}
